# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1582, 980)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonOpenFolder = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/images/res/folder_document.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.buttonOpenFolder.setIcon(icon)
        self.buttonOpenFolder.setIconSize(QtCore.QSize(32, 32))
        self.buttonOpenFolder.setObjectName("buttonOpenFolder")
        self.horizontalLayout.addWidget(self.buttonOpenFolder)
        self.buttonOpenImage = QtWidgets.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/images/res/document_empty.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.buttonOpenImage.setIcon(icon1)
        self.buttonOpenImage.setIconSize(QtCore.QSize(32, 32))
        self.buttonOpenImage.setObjectName("buttonOpenImage")
        self.horizontalLayout.addWidget(self.buttonOpenImage)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/res/etri_ci.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_5.addWidget(self.widget)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelSelectedImageName = QtWidgets.QLabel(self.layoutWidget1)
        self.labelSelectedImageName.setText("")
        self.labelSelectedImageName.setObjectName("labelSelectedImageName")
        self.horizontalLayout_5.addWidget(self.labelSelectedImageName)
        self.buttonSetToZoomView = QtWidgets.QToolButton(self.layoutWidget1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/images/res/set_zoom_view.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.buttonSetToZoomView.setIcon(icon2)
        self.buttonSetToZoomView.setIconSize(QtCore.QSize(16, 16))
        self.buttonSetToZoomView.setCheckable(True)
        self.buttonSetToZoomView.setAutoExclusive(True)
        self.buttonSetToZoomView.setAutoRaise(False)
        self.buttonSetToZoomView.setObjectName("buttonSetToZoomView")
        self.horizontalLayout_5.addWidget(self.buttonSetToZoomView)
        self.buttonSetToFitView = QtWidgets.QToolButton(self.layoutWidget1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/images/res/set_fit_view.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.buttonSetToFitView.setIcon(icon3)
        self.buttonSetToFitView.setIconSize(QtCore.QSize(16, 16))
        self.buttonSetToFitView.setCheckable(True)
        self.buttonSetToFitView.setAutoExclusive(True)
        self.buttonSetToFitView.setAutoRaise(True)
        self.buttonSetToFitView.setObjectName("buttonSetToFitView")
        self.horizontalLayout_5.addWidget(self.buttonSetToFitView)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.labelSelectedImage = SingleImage(self.layoutWidget1)
        self.labelSelectedImage.setStyleSheet("background : rgb(64, 64, 96)")
        self.labelSelectedImage.setText("")
        self.labelSelectedImage.setObjectName("labelSelectedImage")
        self.verticalLayout_3.addWidget(self.labelSelectedImage)
        self.verticalLayout_3.setStretch(1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem1)
        self.buttonDeleteImage = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonDeleteImage.setIconSize(QtCore.QSize(32, 32))
        self.buttonDeleteImage.setObjectName("buttonDeleteImage")
        self.horizontalLayout_4.addWidget(self.buttonDeleteImage)
        self.buttonDeleteAllImages = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonDeleteAllImages.setIconSize(QtCore.QSize(32, 32))
        self.buttonDeleteAllImages.setObjectName("buttonDeleteAllImages")
        self.horizontalLayout_4.addWidget(self.buttonDeleteAllImages)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.listImages = QtWidgets.QListWidget(self.layoutWidget2)
        self.listImages.setStyleSheet("background: rgb(255,255,255)")
        self.listImages.setObjectName("listImages")
        self.verticalLayout.addWidget(self.listImages)
        self.verticalLayout_4.addWidget(self.splitter)
        self.widget_2 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelImageCount = QtWidgets.QLabel(self.widget_2)
        self.labelImageCount.setObjectName("labelImageCount")
        self.horizontalLayout_2.addWidget(self.labelImageCount)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem2)
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonStart = QtWidgets.QPushButton(self.widget_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/images/res/magnifying_glass.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.buttonStart.setIcon(icon4)
        self.buttonStart.setIconSize(QtCore.QSize(32, 32))
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout_2.addWidget(self.buttonStart)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem4)
        self.buttonSaveResult = QtWidgets.QPushButton(self.layoutWidget3)
        self.buttonSaveResult.setObjectName("buttonSaveResult")
        self.horizontalLayout_3.addWidget(self.buttonSaveResult)
        self.buttonClearResult = QtWidgets.QPushButton(self.layoutWidget3)
        self.buttonClearResult.setObjectName("buttonClearResult")
        self.horizontalLayout_3.addWidget(self.buttonClearResult)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listResult = QtWidgets.QTreeView(self.layoutWidget3)
        self.listResult.setRootIsDecorated(True)
        self.listResult.setObjectName("listResult")
        self.verticalLayout_2.addWidget(self.listResult)
        self.widget_3 = QtWidgets.QWidget(self.layoutWidget3)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.labelSuccess = QtWidgets.QLabel(self.widget_3)
        self.labelSuccess.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.labelSuccess.setObjectName("labelSuccess")
        self.gridLayout.addWidget(self.labelSuccess, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.labelFailure = QtWidgets.QLabel(self.widget_3)
        self.labelFailure.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.labelFailure.setObjectName("labelFailure")
        self.gridLayout.addWidget(self.labelFailure, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.labelWorked = QtWidgets.QLabel(self.widget_3)
        self.labelWorked.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.labelWorked.setObjectName("labelWorked")
        self.gridLayout.addWidget(self.labelWorked, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.labelAccuracy = QtWidgets.QLabel(self.widget_3)
        self.labelAccuracy.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.labelAccuracy.setObjectName("labelAccuracy")
        self.gridLayout.addWidget(self.labelAccuracy, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_5.addWidget(self.splitter_2)
        self.verticalLayout_5.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1582, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ETRI 폐렴 진단"))
        self.buttonOpenFolder.setText(_translate("MainWindow", "폴더 오픈"))
        self.buttonOpenImage.setText(_translate("MainWindow", "파일 오픈"))
        self.buttonSetToZoomView.setToolTip(_translate("MainWindow", "확대 보기"))
        self.buttonSetToZoomView.setText(_translate("MainWindow", "..."))
        self.buttonSetToFitView.setToolTip(_translate("MainWindow", "채워서 보기"))
        self.buttonSetToFitView.setText(_translate("MainWindow", "..."))
        self.buttonDeleteImage.setText(_translate("MainWindow", "삭제"))
        self.buttonDeleteAllImages.setText(_translate("MainWindow", "모두 삭제"))
        self.labelImageCount.setText(_translate("MainWindow", "0 Files"))
        self.buttonStart.setText(_translate("MainWindow", "진단 시작"))
        self.label_9.setText(_translate("MainWindow", "진단 결과"))
        self.buttonSaveResult.setText(_translate("MainWindow", "저장"))
        self.buttonClearResult.setText(_translate("MainWindow", "초기화"))
        self.label_3.setText(_translate("MainWindow", "일치"))
        self.labelSuccess.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "불일치"))
        self.labelFailure.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "분석 이미지"))
        self.labelWorked.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "일치율"))
        self.labelAccuracy.setText(_translate("MainWindow", "0.00 %"))


from src.singleImage import SingleImage
import src.resources_rc
