FROM nvcr.io/nvidia/pytorch:21.08-py3

# Required packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && \
    apt install -y zip htop screen libgl1-mesa-glx && \
    apt install -y curl git vim wget tar zip unzip jq && \
    apt clean && rm -rf /var/lib/apt/lists/ && rm -rf /root/.cache && rm -rf /tmp/*
RUN pip install --no-cache-dir seaborn thop

# GitHub repository: https://github.com/WongKinYiu/yolov7.git
RUN git clone https://github.com/WongKinYiu/yolov7.git /model/repo

# Download model(s)
ADD https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-e6e.pt /model/

# Model server
ADD server /model/server
RUN pip install --no-cache-dir -r /model/server/requirements.txt

ENTRYPOINT ["/model/server/entrypoint.sh"]


# -- Examples

# How to test inference (image)
# python /model/repo/detect.py --weights /model/yolov7-e6e.pt --conf 0.25 --img-size 640 --source /model/repo/inference/images/horses.jpg

# How to test inference (video)
# python /model/repo/detect.py --weights /model/yolov7-e6e.pt --conf 0.25 --img-size 640 --source yourvideo.mp4
