# Generated by Django 3.2.25 on 2024-07-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(blank=True, max_length=30, null=True)),
                ('create_user', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.CharField(blank=True, max_length=50, null=True)),
                ('target_info', models.CharField(blank=True, max_length=30, null=True)),
                ('target_engine', models.CharField(blank=True, max_length=30, null=True)),
                ('target_os', models.CharField(blank=True, max_length=50, null=True)),
                ('target_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('target_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('target_memory', models.CharField(blank=True, max_length=50, null=True)),
                ('nfs_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('nfs_path', models.CharField(blank=True, max_length=50, null=True)),
                ('target_host_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('target_host_port', models.CharField(blank=True, max_length=50, null=True)),
                ('target_host_service_port', models.CharField(blank=True, max_length=30, null=True)),
                ('target_image', models.CharField(blank=True, max_length=10485760, null=True)),
            ],
            options={
                'db_table': 'target',
            },
        ),
    ]
