# Generated by Django 3.2.25 on 2024-11-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
