# Generated by Django 3.2 on 2022-11-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('architecture', models.FileField(upload_to='')),
                ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prior', models.IntegerField()),
                ('next', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('order', models.IntegerField(primary_key=True,
                                              serialize=False)),
                ('layer', models.CharField(max_length=200)),
                ('parameters', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pth',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('model_output', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Running',
            fields=[
                ('id', models.IntegerField(primary_key=True,
                                           serialize=False)),
                ('running', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('msg', models.CharField(default='',
                                         max_length=200,
                                         null=True)),
                ('user_id', models.CharField(default='',
                                             max_length=200,
                                             null=True)),
                ('project_id', models.CharField(default='',
                                                max_length=200,
                                                null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('msg', models.CharField(default='',
                                         max_length=200,
                                         null=True)),
                ('user_id', models.CharField(default='',
                                             max_length=200,
                                             null=True)),
                ('project_id', models.CharField(default='',
                                                max_length=200,
                                                null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('msg', models.CharField(default='',
                                         max_length=200,
                                         null=True)),
                ('user_id', models.CharField(default='',
                                             max_length=200,
                                             null=True)),
                ('project_id', models.CharField(default='',
                                                max_length=200,
                                                null=True)),
            ],
        ),
    ]
