# Generated by Django 3.2 on 2022-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='running',
            name='running',
        ),
        migrations.AddField(
            model_name='running',
            name='msg',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='running',
            name='timestamp',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='running',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID'),
        ),
    ]
