# Generated by Django 3.2 on 2023-05-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221104_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sorted_ids', models.TextField()),
            ],
        ),
    ]
