# Generated by Django 3.2 on 2022-10-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='start',
            name='start',
        ),
        migrations.AddField(
            model_name='start',
            name='msg',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='start',
            name='project_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='start',
            name='user_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
