# Generated by Django 3.2 on 2022-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221014_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=200, null=True)),
                ('user_id', models.CharField(default='', max_length=200, null=True)),
                ('project_id', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
