# Generated by Django 3.2 on 2022-10-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='running',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
