# Generated by Django 3.2.25 on 2025-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prior', models.IntegerField()),
                ('next', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('project_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('process_id', models.CharField(blank=True, max_length=50, null=True)),
                ('target', models.CharField(blank=True, default='pc', max_length=50, null=True)),
                ('device', models.CharField(blank=True, default='cpu', max_length=50, null=True)),
                ('dataset', models.CharField(blank=True, default='coco', max_length=50, null=True)),
                ('task', models.CharField(blank=True, default='detection', max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='ready', max_length=10, null=True)),
                ('progress', models.CharField(blank=True, default='unknown', max_length=20, null=True)),
                ('model_type', models.CharField(blank=True, default='not selected', max_length=50, null=True)),
                ('model_size', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('model_viz', models.CharField(blank=True, default='not ready', max_length=50, null=True)),
                ('batch_size', models.IntegerField(blank=True, default=16, null=True)),
                ('batch_multiplier', models.FloatField(blank=True, default=1.0)),
                ('epoch', models.IntegerField(blank=True, default=-1)),
                ('best_acc', models.FloatField(blank=True, default=0.0)),
                ('best_net', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False)),
                ('layer', models.CharField(max_length=200)),
                ('parameters', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('project_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('model_pth', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('model_yml', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
