<template>
  <div style="width: 100%; height: 100%" class="d-flex justify-center aling-center">
    <div style="width: 80%; height: 100%" class="d-flex justify-space-around align-center">
      <div v-for="(flow, index) in workflowNames" :key="`flow-${index}`" style="width: calc(80% / 4)">
        <ProgressIcon
          v-if="flow !== ContainerName.USER_EDITING"
          :text="DisplayName[flow]"
          :status="getStatus(flow)"
          @click="onClick($event, flow)"
        />
        <ProgressIcon v-else :text="DisplayName[flow]" :status="getUserEditingStatus" @click="onUserEditing" />
      </div>
    </div>

    <v-dialog v-model="isUserEditingDialog" max-width="500px">
      <v-card>
        <v-card-title> User Editing </v-card-title>
        <v-card-text>
          <div class="d-flex flex-column" style="gap: 25px">
            <div class="d-flex flex-column" style="width: 100%; gap: 10px">
              <div>Download code generated by "Code Gen"</div>
              <v-btn color="#4a98fb" dark @click="download"> Download </v-btn>
            </div>
            <v-divider />
            <div style="height: 180px; gap: 10px" class="d-flex flex-column">
              <div>Upload User Editing Code (*.zip)</div>
              <DragAndDrop
                :height="'145px'"
                @upload="fileUpload"
                :errorMsg="'zip 형식의 파일을 업로드해 주세요.'"
                :fileType="['zip']"
                :isImage="false"
              />
            </div>
          </div>
        </v-card-text>
      </v-card>
    </v-dialog>
  </div>
</template>
<script>
import Swal from "sweetalert2";
import { mapState } from "vuex";
import { ProjectNamespace } from "@/store/modules/project";

import ProgressIcon from "./progress-icon/ProgressIcon.vue";
import DragAndDrop from "@/modules/common/file-upload/DragAndDrop.vue";

import { DisplayName, ContainerName } from "@/shared/enums";

import { downloadNNModel, uploadNNModel } from "@/api";

import { debounce } from "lodash";

export default {
  components: { ProgressIcon, DragAndDrop },

  props: {
    running: {
      default: null
    },

    status: {
      default: ""
    },

    userEdit: {
      default: false
    },

    workflow: {
      default: () => []
    }
  },

  data() {
    return {
      // runningOrder: ["bms", "yoloe", "codeGen", "imagedeploy"],
      isUserEditingDialog: false,
      DisplayName,
      ContainerName
    };
  },

  computed: {
    ...mapState(ProjectNamespace, ["project"]),

    getUserEditingStatus() {
      return this.running === "imagedeploy" ? "completed" : "preparing";
    },

    workflowNames() {
      return this.workflow.length <= 0 ? [] : this.workflow.map(q => q.workflow_name);
    }
  },

  mounted() {
    this.$EventBus.$on("nnModelDownload", this.downloadHandler);
  },

  methods: {
    onClick(e, container) {
      this.$emit("start", container);

      if (container === ContainerName.VISUALIZATION) {
        this.$emit("showVis2code");
      }
    },

    getStatus(container) {
      if (this.workflow.length <= 0) return;
      // 현재 프로젝트의 실행중인 컨테이너 status
      const projectStatus = this.workflowNames.findIndex(q => q.includes(this.running));

      // 화면에 표시되는 컨테이너의 status
      const compareStatus = this.workflowNames.findIndex(q => q.includes(container));

      if (compareStatus === projectStatus && this.status === "failed") {
        return "failed";
      }

      if (compareStatus < projectStatus) {
        return "completed";
      } else if (
        compareStatus === projectStatus &&
        (this.status === "complete" || this.status === "completed" || this.status === "success")
      ) {
        return "completed";
      } else if (compareStatus === projectStatus) {
        return "running";
      } else {
        return "preparing";
      }
    },

    downloadHandler: debounce(function () {
      this.download();
    }, 1000),

    async download() {
      this.showLoadingPopup();
      await downloadNNModel(this.project.create_user, this.project.id)
        .then(blob => {
          this.blobDownload(blob);
          this.hideLoadingPopup();
          this.isUserEditingDialog = false;
          Swal.fire("다운로드 성공", "", "info");
        })
        .catch(err => {
          console.error("err: ", err);
        });
    },

    blobDownload(blob, fileName = "nn_model.zip") {
      const url = window.URL.createObjectURL(new Blob([blob]));
      const a = document.createElement("a");
      a.href = url;
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
      setTimeout(() => {
        window.URL.revokeObjectURL(url);
      }, 60000);
      a.remove();
    },

    async fileUpload(file) {
      this.showLoadingPopup();

      await uploadNNModel(this.project.create_user, this.project.id, file).then(() => {
        this.hideLoadingPopup();
        this.isUserEditingDialog = false;

        Swal.fire({
          title: `업로드 성공`,
          text: "Image Deploy를 실행하시겠습니까?",
          icon: "info",
          showCancelButton: true,
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "확인",
          cancelButtonText: "취소"
        }).then(async result => {
          if (result.isConfirmed) {
            this.$emit("immediateLaunch", "imagedeploy");
          }
        });
      });
    },

    onUserEditing() {
      this.isUserEditingDialog = true;
    },

    showLoadingPopup() {
      Swal.fire({
        title: "Please Wait....",
        allowOutsideClick: false,
        allowEscapekey: false,
        allowEnterkey: false,
        showConfimButton: false,
        didOpen: () => {
          Swal.showLoading();
        }
      });
    },

    hideLoadingPopup() {
      Swal.close();
    }
  }
};
</script>
<style lang="scss" scoped></style>
