# args.yaml for Yolov9 

# base
weights: ''
cfg: ''
data: ''
hyp: ''
epochs: 500
batch_size: -1  # it'll be changed by auto-batch
img_size: [640, 640]
device: ''

# transfer learning
resume: False
freeze: [0]

# input images
seed: 0
workers: 8
rect: False # rectangular batch for training
multi_scale: False
single_cls: False
image_weights: False
close_mosaic: 15 # do not use mosaic during last 15 epochs

# optimizer
adam: False # optimizer: Adam or SGD
linear_lr: True # schedular: cos_lr if False

# speedy training
cache_images: False
nosave: False
save_period: 1
notest: False
patience: 100

# hpo
evolve: False

# loss/metric
quad: False
noautoanchor: False # check/recompute anchors if True, [note] useless for 'v9'
metric: 'v9' # mAP metirc 'v5' / 'v7' / 'v9'
loss_name: 'TAL' # anchor-free: TAL, anchor: OTA
label_smoothing: 0.0

# ddp
sync_bn: False
local_rank: -1

# save
bucket: ''
project: 'runs/train' # it must be changed to /shared/common/{uid}/{pid}
name: 'autonn'
exist_ok: True # make incremetal directory if False (e.g. autonn1, autonn2, ...)

# logger (not use)
# entity: None
# upload_dataset: False
# bbox_interval: -1
# artifact_alias: 'latest'