# DOCKERFILE_TEMPLATE_DEFAULT = r"""# syntax = docker/dockerfile:1.0-experimental
#FROM --platform=linux/amd64 ultralytics/yolov5:v6.1
FROM ultralytics/yolov5:v6.1
MAINTAINER Backend.AI Manager

# ENV PYTHONUNBUFFERED=1 \
#
#     LANG=C.UTF-8
#
#


ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul


# RUN useradd --user-group --create-home --no-log-init --shell /bin/bash work

RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        wget curl git-core \
        vim-tiny zip unzip \
        python3 python3-pip \
        libssl-dev libgl1-mesa-glx \
        proj-bin libproj-dev \
        libgeos-dev libgeos++-dev libglib2.0-0 \
        mime-support ncurses-term \
             
        gcc g++ &&\

    apt-get clean && \
    rm -rf /var/lib/apt/lists/ && \
    rm -rf /root/.cache && \
    rm -rf /tmp/*

# # RUN ln -sf /usr/share/terminfo/x/xterm-color /usr/share/terminfo/x/xterm-256color
# RUN mkdir /data
# COPY ./tango/common/test123/1 /data
# COPY /var/lib/docker/volumes/tango_shared/_data/common/test123/1 /data
# WORKDIR /data

RUN python3 -m pip install -U pip setuptools && \

    python3 -m pip install Pillow && \
    python3 -m pip install h5py && \
    python3 -m pip install ipython && \
    python3 -m pip install jupyter && \
         

    python3 -m pip install jupyterlab

WORKDIR /
COPY tango/common/test123/1 /data
WORKDIR  /data
RUN python3 -m pip install -r nn_model/requirements.txt



# """  # noqa