# Generated by Django 3.2.12 on 2022-10-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderAccesstoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_accesstoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('redirect_uris', models.TextField()),
                ('client_type', models.CharField(max_length=32)),
                ('authorization_grant_type', models.CharField(max_length=32)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('skip_authorization', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('algorithm', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'oauth2_provider_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderIdtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.UUIDField(unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_idtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderRefreshtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('revoked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth2_provider_refreshtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=30, null=True)),
                ('project_description', models.CharField(blank=True, max_length=200, null=True)),
                ('create_user', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.CharField(blank=True, max_length=50, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('target_yaml_path', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('dataset_path', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('data_yaml_path', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('step', models.IntegerField(blank=True, default=0, null=True)),
                ('step_status', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(blank=True, max_length=30, null=True)),
                ('create_user', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.CharField(blank=True, max_length=50, null=True)),
                ('target_cpu', models.CharField(blank=True, max_length=200, null=True)),
                ('target_gpu', models.CharField(blank=True, max_length=200, null=True)),
                ('target_memory', models.CharField(blank=True, max_length=200, null=True)),
                ('target_model', models.CharField(blank=True, max_length=200, null=True)),
                ('target_image', models.CharField(blank=True, max_length=10485760, null=True)),
            ],
            options={
                'db_table': 'target',
            },
        ),
    ]
