# Generated by Django 3.2.25 on 2024-07-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autonn_retry_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trainlosslaststep',
            name='box',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainlosslaststep',
            name='cls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainlosslaststep',
            name='obj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainlosslaststep',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainlosslatest',
            name='box',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainlosslatest',
            name='cls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainlosslatest',
            name='obj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainlosslatest',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valaccuracylaststep',
            name='P',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valaccuracylaststep',
            name='R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valaccuracylaststep',
            name='mAP50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valaccuracylaststep',
            name='mAP50_95',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valaccuracylatest',
            name='P',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valaccuracylatest',
            name='R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valaccuracylatest',
            name='mAP50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valaccuracylatest',
            name='mAP50_95',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
