# Generated by Django 3.2.25 on 2024-07-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0002_auto_20240710_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpochSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_epoch', models.IntegerField(blank=True, default=0, null=True)),
                ('current_epoch', models.IntegerField(blank=True, default=0, null=True)),
                ('train_loss_box', models.FloatField(blank=True, default=0.0, null=True)),
                ('train_loss_obj', models.FloatField(blank=True, default=0.0, null=True)),
                ('train_loss_cls', models.FloatField(blank=True, default=0.0, null=True)),
                ('train_loss_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('val_acc_P', models.FloatField(blank=True, default=0.0, null=True)),
                ('val_acc_R', models.FloatField(blank=True, default=0.0, null=True)),
                ('val_acc_map50', models.FloatField(blank=True, default=0.0, null=True)),
                ('val_acc_map', models.FloatField(blank=True, default=0.0, null=True)),
                ('epoch_time', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_time', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'db_table': 'epoch_summary',
            },
        ),
        migrations.AddField(
            model_name='autonnstatus',
            name='epoch_summary',
            field=models.ForeignKey(blank=True, db_column='epoch_summary', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epoch_summary', to='tango.epochsummary'),
        ),
    ]
