# Generated by Django 3.2.25 on 2024-07-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0003_auto_20240711_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autonnstatus',
            name='epoch_summary',
        ),
        migrations.AddField(
            model_name='epochsummary',
            name='is_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='epochsummary',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='epochsummary',
            name='project_version',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
