# Generated by Django 3.2.25 on 2024-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0004_auto_20240711_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsummary',
            name='FLOPS',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
