# Generated by Django 3.2.25 on 2024-07-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0005_alter_modelsummary_flops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsummary',
            name='FLOPS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
