# Generated by Django 3.2.25 on 2024-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0006_alter_modelsummary_flops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsummary',
            name='FLOPS',
        ),
        migrations.AddField(
            model_name='modelsummary',
            name='flops',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
