# Generated by Django 3.2.25 on 2024-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0007_auto_20240712_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('project_update_cycle', models.IntegerField(default=10)),
                ('autton_update_cycle', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user_setting',
            },
        ),
    ]
