# Generated by Django 3.2.25 on 2024-08-22 06:45

from django.db import migrations, models
import tango.enums


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0008_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='learning_type',
            field=models.CharField(blank=True, default=tango.enums.LearningType['NORMAL'], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='weight_file',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
