@startuml
'https://plantuml.com/class-diagram

interface MemberService
interface MemberRepository
class MemoryMemberRepository

MemberRepository -- MemberService
MemberRepository <|-- MemoryMemberRepository

@enduml
